#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioData_Update
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AppraisalDb")]
	public partial class AppraisalConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertzib_workflow_master(zib_workflow_master instance);
    partial void Updatezib_workflow_master(zib_workflow_master instance);
    partial void Deletezib_workflow_master(zib_workflow_master instance);
    partial void Insertzib_passport_approver(zib_passport_approver instance);
    partial void Updatezib_passport_approver(zib_passport_approver instance);
    partial void Deletezib_passport_approver(zib_passport_approver instance);
    partial void Insertzib_workflow_user_role(zib_workflow_user_role instance);
    partial void Updatezib_workflow_user_role(zib_workflow_user_role instance);
    partial void Deletezib_workflow_user_role(zib_workflow_user_role instance);
    partial void Insertzib_passportentry(zib_passportentry instance);
    partial void Updatezib_passportentry(zib_passportentry instance);
    partial void Deletezib_passportentry(zib_passportentry instance);
    #endregion
		
		public AppraisalConnectionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AppraisalDbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AppraisalConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppraisalConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppraisalConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppraisalConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<zib_workflow_master> zib_workflow_masters
		{
			get
			{
				return this.GetTable<zib_workflow_master>();
			}
		}
		
		public System.Data.Linq.Table<zib_workflow_stage> zib_workflow_stages
		{
			get
			{
				return this.GetTable<zib_workflow_stage>();
			}
		}
		
		public System.Data.Linq.Table<zib_passport_approver> zib_passport_approvers
		{
			get
			{
				return this.GetTable<zib_passport_approver>();
			}
		}
		
		public System.Data.Linq.Table<zib_workflow_user_role> zib_workflow_user_roles
		{
			get
			{
				return this.GetTable<zib_workflow_user_role>();
			}
		}
		
		public System.Data.Linq.Table<zib_workflow_link_role_permission> zib_workflow_link_role_permissions
		{
			get
			{
				return this.GetTable<zib_workflow_link_role_permission>();
			}
		}
		
		public System.Data.Linq.Table<zib_workflow_user_permission> zib_workflow_user_permissions
		{
			get
			{
				return this.GetTable<zib_workflow_user_permission>();
			}
		}
		
		public System.Data.Linq.Table<zib_workflow_approver_role> zib_workflow_approver_roles
		{
			get
			{
				return this.GetTable<zib_workflow_approver_role>();
			}
		}
		
		public System.Data.Linq.Table<zib_passportentry> zib_passportentries
		{
			get
			{
				return this.GetTable<zib_passportentry>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_workflow_master")]
	public partial class zib_workflow_master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _appid;
		
		private string _workflowid;
		
		private int _requeststageid;
		
		private string _requeststage;
		
		private string _requeststatus;
		
		private System.DateTime _createdt;
		
		private System.DateTime _editdt;
		
		private string _lastapprovername;
		
		private string _lastapprovernumber;
		
		private string _initiatorname;
		
		private string _initiatornumber;
		
		private string _unitname;
		
		private string _unitcode;
		
		private string _deptname;
		
		private string _deptcode;
		
		private string _groupname;
		
		private string _groupcode;
		
		private string _supergroupname;
		
		private string _supergroupcode;
		
		private System.Xml.Linq.XElement _approvalhistory;
		
		private System.Xml.Linq.XElement _audithistory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnappidChanging(string value);
    partial void OnappidChanged();
    partial void OnworkflowidChanging(string value);
    partial void OnworkflowidChanged();
    partial void OnrequeststageidChanging(int value);
    partial void OnrequeststageidChanged();
    partial void OnrequeststageChanging(string value);
    partial void OnrequeststageChanged();
    partial void OnrequeststatusChanging(string value);
    partial void OnrequeststatusChanged();
    partial void OncreatedtChanging(System.DateTime value);
    partial void OncreatedtChanged();
    partial void OneditdtChanging(System.DateTime value);
    partial void OneditdtChanged();
    partial void OnlastapprovernameChanging(string value);
    partial void OnlastapprovernameChanged();
    partial void OnlastapprovernumberChanging(string value);
    partial void OnlastapprovernumberChanged();
    partial void OninitiatornameChanging(string value);
    partial void OninitiatornameChanged();
    partial void OninitiatornumberChanging(string value);
    partial void OninitiatornumberChanged();
    partial void OnunitnameChanging(string value);
    partial void OnunitnameChanged();
    partial void OnunitcodeChanging(string value);
    partial void OnunitcodeChanged();
    partial void OndeptnameChanging(string value);
    partial void OndeptnameChanged();
    partial void OndeptcodeChanging(string value);
    partial void OndeptcodeChanged();
    partial void OngroupnameChanging(string value);
    partial void OngroupnameChanged();
    partial void OngroupcodeChanging(string value);
    partial void OngroupcodeChanged();
    partial void OnsupergroupnameChanging(string value);
    partial void OnsupergroupnameChanged();
    partial void OnsupergroupcodeChanging(string value);
    partial void OnsupergroupcodeChanged();
    partial void OnapprovalhistoryChanging(System.Xml.Linq.XElement value);
    partial void OnapprovalhistoryChanged();
    partial void OnaudithistoryChanging(System.Xml.Linq.XElement value);
    partial void OnaudithistoryChanged();
    #endregion
		
		public zib_workflow_master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string appid
		{
			get
			{
				return this._appid;
			}
			set
			{
				if ((this._appid != value))
				{
					this.OnappidChanging(value);
					this.SendPropertyChanging();
					this._appid = value;
					this.SendPropertyChanged("appid");
					this.OnappidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workflowid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string workflowid
		{
			get
			{
				return this._workflowid;
			}
			set
			{
				if ((this._workflowid != value))
				{
					this.OnworkflowidChanging(value);
					this.SendPropertyChanging();
					this._workflowid = value;
					this.SendPropertyChanged("workflowid");
					this.OnworkflowidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststageid", DbType="Int NOT NULL")]
		public int requeststageid
		{
			get
			{
				return this._requeststageid;
			}
			set
			{
				if ((this._requeststageid != value))
				{
					this.OnrequeststageidChanging(value);
					this.SendPropertyChanging();
					this._requeststageid = value;
					this.SendPropertyChanged("requeststageid");
					this.OnrequeststageidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststage
		{
			get
			{
				return this._requeststage;
			}
			set
			{
				if ((this._requeststage != value))
				{
					this.OnrequeststageChanging(value);
					this.SendPropertyChanging();
					this._requeststage = value;
					this.SendPropertyChanged("requeststage");
					this.OnrequeststageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststatus
		{
			get
			{
				return this._requeststatus;
			}
			set
			{
				if ((this._requeststatus != value))
				{
					this.OnrequeststatusChanging(value);
					this.SendPropertyChanging();
					this._requeststatus = value;
					this.SendPropertyChanged("requeststatus");
					this.OnrequeststatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime NOT NULL")]
		public System.DateTime createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editdt", DbType="DateTime NOT NULL")]
		public System.DateTime editdt
		{
			get
			{
				return this._editdt;
			}
			set
			{
				if ((this._editdt != value))
				{
					this.OneditdtChanging(value);
					this.SendPropertyChanging();
					this._editdt = value;
					this.SendPropertyChanged("editdt");
					this.OneditdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastapprovername", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lastapprovername
		{
			get
			{
				return this._lastapprovername;
			}
			set
			{
				if ((this._lastapprovername != value))
				{
					this.OnlastapprovernameChanging(value);
					this.SendPropertyChanging();
					this._lastapprovername = value;
					this.SendPropertyChanged("lastapprovername");
					this.OnlastapprovernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastapprovernumber", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string lastapprovernumber
		{
			get
			{
				return this._lastapprovernumber;
			}
			set
			{
				if ((this._lastapprovernumber != value))
				{
					this.OnlastapprovernumberChanging(value);
					this.SendPropertyChanging();
					this._lastapprovernumber = value;
					this.SendPropertyChanged("lastapprovernumber");
					this.OnlastapprovernumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiatorname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string initiatorname
		{
			get
			{
				return this._initiatorname;
			}
			set
			{
				if ((this._initiatorname != value))
				{
					this.OninitiatornameChanging(value);
					this.SendPropertyChanging();
					this._initiatorname = value;
					this.SendPropertyChanged("initiatorname");
					this.OninitiatornameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiatornumber", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string initiatornumber
		{
			get
			{
				return this._initiatornumber;
			}
			set
			{
				if ((this._initiatornumber != value))
				{
					this.OninitiatornumberChanging(value);
					this.SendPropertyChanging();
					this._initiatornumber = value;
					this.SendPropertyChanged("initiatornumber");
					this.OninitiatornumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this.OnunitnameChanging(value);
					this.SendPropertyChanging();
					this._unitname = value;
					this.SendPropertyChanged("unitname");
					this.OnunitnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string unitcode
		{
			get
			{
				return this._unitcode;
			}
			set
			{
				if ((this._unitcode != value))
				{
					this.OnunitcodeChanging(value);
					this.SendPropertyChanging();
					this._unitcode = value;
					this.SendPropertyChanged("unitcode");
					this.OnunitcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this.OndeptnameChanging(value);
					this.SendPropertyChanging();
					this._deptname = value;
					this.SendPropertyChanged("deptname");
					this.OndeptnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this.OndeptcodeChanging(value);
					this.SendPropertyChanging();
					this._deptcode = value;
					this.SendPropertyChanged("deptcode");
					this.OndeptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string groupname
		{
			get
			{
				return this._groupname;
			}
			set
			{
				if ((this._groupname != value))
				{
					this.OngroupnameChanging(value);
					this.SendPropertyChanging();
					this._groupname = value;
					this.SendPropertyChanged("groupname");
					this.OngroupnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string groupcode
		{
			get
			{
				return this._groupcode;
			}
			set
			{
				if ((this._groupcode != value))
				{
					this.OngroupcodeChanging(value);
					this.SendPropertyChanging();
					this._groupcode = value;
					this.SendPropertyChanged("groupcode");
					this.OngroupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string supergroupname
		{
			get
			{
				return this._supergroupname;
			}
			set
			{
				if ((this._supergroupname != value))
				{
					this.OnsupergroupnameChanging(value);
					this.SendPropertyChanging();
					this._supergroupname = value;
					this.SendPropertyChanged("supergroupname");
					this.OnsupergroupnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string supergroupcode
		{
			get
			{
				return this._supergroupcode;
			}
			set
			{
				if ((this._supergroupcode != value))
				{
					this.OnsupergroupcodeChanging(value);
					this.SendPropertyChanging();
					this._supergroupcode = value;
					this.SendPropertyChanged("supergroupcode");
					this.OnsupergroupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approvalhistory", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement approvalhistory
		{
			get
			{
				return this._approvalhistory;
			}
			set
			{
				if ((this._approvalhistory != value))
				{
					this.OnapprovalhistoryChanging(value);
					this.SendPropertyChanging();
					this._approvalhistory = value;
					this.SendPropertyChanged("approvalhistory");
					this.OnapprovalhistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_audithistory", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement audithistory
		{
			get
			{
				return this._audithistory;
			}
			set
			{
				if ((this._audithistory != value))
				{
					this.OnaudithistoryChanging(value);
					this.SendPropertyChanging();
					this._audithistory = value;
					this.SendPropertyChanged("audithistory");
					this.OnaudithistoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_workflow_stages")]
	public partial class zib_workflow_stage
	{
		
		private string _appid;
		
		private string _requeststage;
		
		private int _requeststageid;
		
		private int _maxstages;
		
		private string _deptcode;
		
		public zib_workflow_stage()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string appid
		{
			get
			{
				return this._appid;
			}
			set
			{
				if ((this._appid != value))
				{
					this._appid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststage
		{
			get
			{
				return this._requeststage;
			}
			set
			{
				if ((this._requeststage != value))
				{
					this._requeststage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststageid", DbType="Int NOT NULL")]
		public int requeststageid
		{
			get
			{
				return this._requeststageid;
			}
			set
			{
				if ((this._requeststageid != value))
				{
					this._requeststageid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxstages", DbType="Int NOT NULL")]
		public int maxstages
		{
			get
			{
				return this._maxstages;
			}
			set
			{
				if ((this._maxstages != value))
				{
					this._maxstages = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50)")]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this._deptcode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_passport_approvers")]
	public partial class zib_passport_approver : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _entrykey;
		
		private string _unitcode;
		
		private string _unitname;
		
		private string _deptcode;
		
		private string _deptname;
		
		private string _groupcode;
		
		private string _groupname;
		
		private string _supergroupcode;
		
		private string _supergroupname;
		
		private int _roleid;
		
		private string _role;
		
		private string _approverid;
		
		private string _approvername;
		
		private System.DateTime _createdt;
		
		private string _createdbyid;
		
		private System.DateTime _editdate;
		
		private string _edittedbyid;
		
		private string _comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnentrykeyChanging(string value);
    partial void OnentrykeyChanged();
    partial void OnunitcodeChanging(string value);
    partial void OnunitcodeChanged();
    partial void OnunitnameChanging(string value);
    partial void OnunitnameChanged();
    partial void OndeptcodeChanging(string value);
    partial void OndeptcodeChanged();
    partial void OndeptnameChanging(string value);
    partial void OndeptnameChanged();
    partial void OngroupcodeChanging(string value);
    partial void OngroupcodeChanged();
    partial void OngroupnameChanging(string value);
    partial void OngroupnameChanged();
    partial void OnsupergroupcodeChanging(string value);
    partial void OnsupergroupcodeChanged();
    partial void OnsupergroupnameChanging(string value);
    partial void OnsupergroupnameChanged();
    partial void OnroleidChanging(int value);
    partial void OnroleidChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnapproveridChanging(string value);
    partial void OnapproveridChanged();
    partial void OnapprovernameChanging(string value);
    partial void OnapprovernameChanged();
    partial void OncreatedtChanging(System.DateTime value);
    partial void OncreatedtChanged();
    partial void OncreatedbyidChanging(string value);
    partial void OncreatedbyidChanged();
    partial void OneditdateChanging(System.DateTime value);
    partial void OneditdateChanged();
    partial void OnedittedbyidChanging(string value);
    partial void OnedittedbyidChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    #endregion
		
		public zib_passport_approver()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrykey", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string entrykey
		{
			get
			{
				return this._entrykey;
			}
			set
			{
				if ((this._entrykey != value))
				{
					this.OnentrykeyChanging(value);
					this.SendPropertyChanging();
					this._entrykey = value;
					this.SendPropertyChanged("entrykey");
					this.OnentrykeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string unitcode
		{
			get
			{
				return this._unitcode;
			}
			set
			{
				if ((this._unitcode != value))
				{
					this.OnunitcodeChanging(value);
					this.SendPropertyChanging();
					this._unitcode = value;
					this.SendPropertyChanged("unitcode");
					this.OnunitcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this.OnunitnameChanging(value);
					this.SendPropertyChanging();
					this._unitname = value;
					this.SendPropertyChanged("unitname");
					this.OnunitnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this.OndeptcodeChanging(value);
					this.SendPropertyChanging();
					this._deptcode = value;
					this.SendPropertyChanged("deptcode");
					this.OndeptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this.OndeptnameChanging(value);
					this.SendPropertyChanging();
					this._deptname = value;
					this.SendPropertyChanged("deptname");
					this.OndeptnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string groupcode
		{
			get
			{
				return this._groupcode;
			}
			set
			{
				if ((this._groupcode != value))
				{
					this.OngroupcodeChanging(value);
					this.SendPropertyChanging();
					this._groupcode = value;
					this.SendPropertyChanged("groupcode");
					this.OngroupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string groupname
		{
			get
			{
				return this._groupname;
			}
			set
			{
				if ((this._groupname != value))
				{
					this.OngroupnameChanging(value);
					this.SendPropertyChanging();
					this._groupname = value;
					this.SendPropertyChanged("groupname");
					this.OngroupnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string supergroupcode
		{
			get
			{
				return this._supergroupcode;
			}
			set
			{
				if ((this._supergroupcode != value))
				{
					this.OnsupergroupcodeChanging(value);
					this.SendPropertyChanging();
					this._supergroupcode = value;
					this.SendPropertyChanged("supergroupcode");
					this.OnsupergroupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string supergroupname
		{
			get
			{
				return this._supergroupname;
			}
			set
			{
				if ((this._supergroupname != value))
				{
					this.OnsupergroupnameChanging(value);
					this.SendPropertyChanging();
					this._supergroupname = value;
					this.SendPropertyChanged("supergroupname");
					this.OnsupergroupnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="Int NOT NULL")]
		public int roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approverid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string approverid
		{
			get
			{
				return this._approverid;
			}
			set
			{
				if ((this._approverid != value))
				{
					this.OnapproveridChanging(value);
					this.SendPropertyChanging();
					this._approverid = value;
					this.SendPropertyChanged("approverid");
					this.OnapproveridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approvername", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string approvername
		{
			get
			{
				return this._approvername;
			}
			set
			{
				if ((this._approvername != value))
				{
					this.OnapprovernameChanging(value);
					this.SendPropertyChanging();
					this._approvername = value;
					this.SendPropertyChanged("approvername");
					this.OnapprovernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime NOT NULL")]
		public System.DateTime createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdbyid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string createdbyid
		{
			get
			{
				return this._createdbyid;
			}
			set
			{
				if ((this._createdbyid != value))
				{
					this.OncreatedbyidChanging(value);
					this.SendPropertyChanging();
					this._createdbyid = value;
					this.SendPropertyChanged("createdbyid");
					this.OncreatedbyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editdate", DbType="DateTime NOT NULL")]
		public System.DateTime editdate
		{
			get
			{
				return this._editdate;
			}
			set
			{
				if ((this._editdate != value))
				{
					this.OneditdateChanging(value);
					this.SendPropertyChanging();
					this._editdate = value;
					this.SendPropertyChanged("editdate");
					this.OneditdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edittedbyid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string edittedbyid
		{
			get
			{
				return this._edittedbyid;
			}
			set
			{
				if ((this._edittedbyid != value))
				{
					this.OnedittedbyidChanging(value);
					this.SendPropertyChanging();
					this._edittedbyid = value;
					this.SendPropertyChanged("edittedbyid");
					this.OnedittedbyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="VarChar(100)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_workflow_user_roles")]
	public partial class zib_workflow_user_role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _entrykey;
		
		private int _roleid;
		
		private string _role;
		
		private string _username;
		
		private string _employee_number;
		
		private string _appid;
		
		private string _name;
		
		private string _status;
		
		private string _description;
		
		private string _createdbyid;
		
		private string _editedbyid;
		
		private System.DateTime _createdt;
		
		private System.DateTime _editdt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnentrykeyChanging(string value);
    partial void OnentrykeyChanged();
    partial void OnroleidChanging(int value);
    partial void OnroleidChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onemployee_numberChanging(string value);
    partial void Onemployee_numberChanged();
    partial void OnappidChanging(string value);
    partial void OnappidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OncreatedbyidChanging(string value);
    partial void OncreatedbyidChanged();
    partial void OneditedbyidChanging(string value);
    partial void OneditedbyidChanged();
    partial void OncreatedtChanging(System.DateTime value);
    partial void OncreatedtChanged();
    partial void OneditdtChanging(System.DateTime value);
    partial void OneditdtChanged();
    #endregion
		
		public zib_workflow_user_role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrykey", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string entrykey
		{
			get
			{
				return this._entrykey;
			}
			set
			{
				if ((this._entrykey != value))
				{
					this.OnentrykeyChanging(value);
					this.SendPropertyChanging();
					this._entrykey = value;
					this.SendPropertyChanged("entrykey");
					this.OnentrykeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="Int NOT NULL")]
		public int roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string employee_number
		{
			get
			{
				return this._employee_number;
			}
			set
			{
				if ((this._employee_number != value))
				{
					this.Onemployee_numberChanging(value);
					this.SendPropertyChanging();
					this._employee_number = value;
					this.SendPropertyChanged("employee_number");
					this.Onemployee_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string appid
		{
			get
			{
				return this._appid;
			}
			set
			{
				if ((this._appid != value))
				{
					this.OnappidChanging(value);
					this.SendPropertyChanging();
					this._appid = value;
					this.SendPropertyChanged("appid");
					this.OnappidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdbyid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string createdbyid
		{
			get
			{
				return this._createdbyid;
			}
			set
			{
				if ((this._createdbyid != value))
				{
					this.OncreatedbyidChanging(value);
					this.SendPropertyChanging();
					this._createdbyid = value;
					this.SendPropertyChanged("createdbyid");
					this.OncreatedbyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editedbyid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string editedbyid
		{
			get
			{
				return this._editedbyid;
			}
			set
			{
				if ((this._editedbyid != value))
				{
					this.OneditedbyidChanging(value);
					this.SendPropertyChanging();
					this._editedbyid = value;
					this.SendPropertyChanged("editedbyid");
					this.OneditedbyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime NOT NULL")]
		public System.DateTime createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editdt", DbType="DateTime NOT NULL")]
		public System.DateTime editdt
		{
			get
			{
				return this._editdt;
			}
			set
			{
				if ((this._editdt != value))
				{
					this.OneditdtChanging(value);
					this.SendPropertyChanging();
					this._editdt = value;
					this.SendPropertyChanged("editdt");
					this.OneditdtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_workflow_link_role_permission")]
	public partial class zib_workflow_link_role_permission
	{
		
		private int _role_id;
		
		private int _permission_id;
		
		public zib_workflow_link_role_permission()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", DbType="Int NOT NULL")]
		public int role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					this._role_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_id", DbType="Int NOT NULL")]
		public int permission_id
		{
			get
			{
				return this._permission_id;
			}
			set
			{
				if ((this._permission_id != value))
				{
					this._permission_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_workflow_user_permission")]
	public partial class zib_workflow_user_permission
	{
		
		private int _permission_id;
		
		private string _permission_description;
		
		public zib_workflow_user_permission()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_id", DbType="Int NOT NULL")]
		public int permission_id
		{
			get
			{
				return this._permission_id;
			}
			set
			{
				if ((this._permission_id != value))
				{
					this._permission_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string permission_description
		{
			get
			{
				return this._permission_description;
			}
			set
			{
				if ((this._permission_description != value))
				{
					this._permission_description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_workflow_approver_roles")]
	public partial class zib_workflow_approver_role
	{
		
		private string _role;
		
		private int _roleid;
		
		private string _dept;
		
		private string _deptcode;
		
		private string _description;
		
		public zib_workflow_approver_role()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this._role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="Int NOT NULL")]
		public int roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this._roleid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dept
		{
			get
			{
				return this._dept;
			}
			set
			{
				if ((this._dept != value))
				{
					this._dept = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this._deptcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_passportentries")]
	public partial class zib_passportentry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _entry_key;
		
		private string _workflowid;
		
		private int _requeststageid;
		
		private string _requeststage;
		
		private System.DateTime _requestdate;
		
		private string _employee_number;
		
		private string _name;
		
		private string _grade;
		
		private string _branchname;
		
		private string _branchcode;
		
		private string _deptname;
		
		private string _deptcode;
		
		private string _passportType;
		
		private string _passportNumber;
		
		private string _passportSurname;
		
		private string _passportOtherNames;
		
		private string _passportSex;
		
		private string _passportCountry;
		
		private string _passportCountryCode;
		
		private System.DateTime _passportDateOfBirth;
		
		private string _passportPlaceOfBirth;
		
		private string _passportAuthority;
		
		private System.DateTime _passportDateOfIssue;
		
		private System.DateTime _passportDateOfExpiry;
		
		private string _passportFileName;
		
		private string _passportContentType;
		
		private System.Data.Linq.Binary _passportBytes;
		
		private System.DateTime _createdt;
		
		private string _passport_status;
		
		private string _hr_uploader_name;
		
		private string _hr_uploader_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onentry_keyChanging(string value);
    partial void Onentry_keyChanged();
    partial void OnworkflowidChanging(string value);
    partial void OnworkflowidChanged();
    partial void OnrequeststageidChanging(int value);
    partial void OnrequeststageidChanged();
    partial void OnrequeststageChanging(string value);
    partial void OnrequeststageChanged();
    partial void OnrequestdateChanging(System.DateTime value);
    partial void OnrequestdateChanged();
    partial void Onemployee_numberChanging(string value);
    partial void Onemployee_numberChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngradeChanging(string value);
    partial void OngradeChanged();
    partial void OnbranchnameChanging(string value);
    partial void OnbranchnameChanged();
    partial void OnbranchcodeChanging(string value);
    partial void OnbranchcodeChanged();
    partial void OndeptnameChanging(string value);
    partial void OndeptnameChanged();
    partial void OndeptcodeChanging(string value);
    partial void OndeptcodeChanged();
    partial void OnpassportTypeChanging(string value);
    partial void OnpassportTypeChanged();
    partial void OnpassportNumberChanging(string value);
    partial void OnpassportNumberChanged();
    partial void OnpassportSurnameChanging(string value);
    partial void OnpassportSurnameChanged();
    partial void OnpassportOtherNamesChanging(string value);
    partial void OnpassportOtherNamesChanged();
    partial void OnpassportSexChanging(string value);
    partial void OnpassportSexChanged();
    partial void OnpassportCountryChanging(string value);
    partial void OnpassportCountryChanged();
    partial void OnpassportCountryCodeChanging(string value);
    partial void OnpassportCountryCodeChanged();
    partial void OnpassportDateOfBirthChanging(System.DateTime value);
    partial void OnpassportDateOfBirthChanged();
    partial void OnpassportPlaceOfBirthChanging(string value);
    partial void OnpassportPlaceOfBirthChanged();
    partial void OnpassportAuthorityChanging(string value);
    partial void OnpassportAuthorityChanged();
    partial void OnpassportDateOfIssueChanging(System.DateTime value);
    partial void OnpassportDateOfIssueChanged();
    partial void OnpassportDateOfExpiryChanging(System.DateTime value);
    partial void OnpassportDateOfExpiryChanged();
    partial void OnpassportFileNameChanging(string value);
    partial void OnpassportFileNameChanged();
    partial void OnpassportContentTypeChanging(string value);
    partial void OnpassportContentTypeChanged();
    partial void OnpassportBytesChanging(System.Data.Linq.Binary value);
    partial void OnpassportBytesChanged();
    partial void OncreatedtChanging(System.DateTime value);
    partial void OncreatedtChanged();
    partial void Onpassport_statusChanging(string value);
    partial void Onpassport_statusChanged();
    partial void Onhr_uploader_nameChanging(string value);
    partial void Onhr_uploader_nameChanged();
    partial void Onhr_uploader_idChanging(string value);
    partial void Onhr_uploader_idChanged();
    #endregion
		
		public zib_passportentry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_key", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string entry_key
		{
			get
			{
				return this._entry_key;
			}
			set
			{
				if ((this._entry_key != value))
				{
					this.Onentry_keyChanging(value);
					this.SendPropertyChanging();
					this._entry_key = value;
					this.SendPropertyChanged("entry_key");
					this.Onentry_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workflowid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string workflowid
		{
			get
			{
				return this._workflowid;
			}
			set
			{
				if ((this._workflowid != value))
				{
					this.OnworkflowidChanging(value);
					this.SendPropertyChanging();
					this._workflowid = value;
					this.SendPropertyChanged("workflowid");
					this.OnworkflowidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststageid", DbType="Int NOT NULL")]
		public int requeststageid
		{
			get
			{
				return this._requeststageid;
			}
			set
			{
				if ((this._requeststageid != value))
				{
					this.OnrequeststageidChanging(value);
					this.SendPropertyChanging();
					this._requeststageid = value;
					this.SendPropertyChanged("requeststageid");
					this.OnrequeststageidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststage
		{
			get
			{
				return this._requeststage;
			}
			set
			{
				if ((this._requeststage != value))
				{
					this.OnrequeststageChanging(value);
					this.SendPropertyChanging();
					this._requeststage = value;
					this.SendPropertyChanged("requeststage");
					this.OnrequeststageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requestdate", DbType="DateTime NOT NULL")]
		public System.DateTime requestdate
		{
			get
			{
				return this._requestdate;
			}
			set
			{
				if ((this._requestdate != value))
				{
					this.OnrequestdateChanging(value);
					this.SendPropertyChanging();
					this._requestdate = value;
					this.SendPropertyChanged("requestdate");
					this.OnrequestdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string employee_number
		{
			get
			{
				return this._employee_number;
			}
			set
			{
				if ((this._employee_number != value))
				{
					this.Onemployee_numberChanging(value);
					this.SendPropertyChanging();
					this._employee_number = value;
					this.SendPropertyChanged("employee_number");
					this.Onemployee_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchname", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string branchname
		{
			get
			{
				return this._branchname;
			}
			set
			{
				if ((this._branchname != value))
				{
					this.OnbranchnameChanging(value);
					this.SendPropertyChanging();
					this._branchname = value;
					this.SendPropertyChanged("branchname");
					this.OnbranchnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchcode", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string branchcode
		{
			get
			{
				return this._branchcode;
			}
			set
			{
				if ((this._branchcode != value))
				{
					this.OnbranchcodeChanging(value);
					this.SendPropertyChanging();
					this._branchcode = value;
					this.SendPropertyChanged("branchcode");
					this.OnbranchcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this.OndeptnameChanging(value);
					this.SendPropertyChanging();
					this._deptname = value;
					this.SendPropertyChanged("deptname");
					this.OndeptnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this.OndeptcodeChanging(value);
					this.SendPropertyChanging();
					this._deptcode = value;
					this.SendPropertyChanged("deptcode");
					this.OndeptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string passportType
		{
			get
			{
				return this._passportType;
			}
			set
			{
				if ((this._passportType != value))
				{
					this.OnpassportTypeChanging(value);
					this.SendPropertyChanging();
					this._passportType = value;
					this.SendPropertyChanged("passportType");
					this.OnpassportTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportNumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string passportNumber
		{
			get
			{
				return this._passportNumber;
			}
			set
			{
				if ((this._passportNumber != value))
				{
					this.OnpassportNumberChanging(value);
					this.SendPropertyChanging();
					this._passportNumber = value;
					this.SendPropertyChanged("passportNumber");
					this.OnpassportNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportSurname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string passportSurname
		{
			get
			{
				return this._passportSurname;
			}
			set
			{
				if ((this._passportSurname != value))
				{
					this.OnpassportSurnameChanging(value);
					this.SendPropertyChanging();
					this._passportSurname = value;
					this.SendPropertyChanged("passportSurname");
					this.OnpassportSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportOtherNames", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string passportOtherNames
		{
			get
			{
				return this._passportOtherNames;
			}
			set
			{
				if ((this._passportOtherNames != value))
				{
					this.OnpassportOtherNamesChanging(value);
					this.SendPropertyChanging();
					this._passportOtherNames = value;
					this.SendPropertyChanged("passportOtherNames");
					this.OnpassportOtherNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportSex", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string passportSex
		{
			get
			{
				return this._passportSex;
			}
			set
			{
				if ((this._passportSex != value))
				{
					this.OnpassportSexChanging(value);
					this.SendPropertyChanging();
					this._passportSex = value;
					this.SendPropertyChanged("passportSex");
					this.OnpassportSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportCountry", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string passportCountry
		{
			get
			{
				return this._passportCountry;
			}
			set
			{
				if ((this._passportCountry != value))
				{
					this.OnpassportCountryChanging(value);
					this.SendPropertyChanging();
					this._passportCountry = value;
					this.SendPropertyChanged("passportCountry");
					this.OnpassportCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportCountryCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string passportCountryCode
		{
			get
			{
				return this._passportCountryCode;
			}
			set
			{
				if ((this._passportCountryCode != value))
				{
					this.OnpassportCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._passportCountryCode = value;
					this.SendPropertyChanged("passportCountryCode");
					this.OnpassportCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportDateOfBirth", DbType="DateTime NOT NULL")]
		public System.DateTime passportDateOfBirth
		{
			get
			{
				return this._passportDateOfBirth;
			}
			set
			{
				if ((this._passportDateOfBirth != value))
				{
					this.OnpassportDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._passportDateOfBirth = value;
					this.SendPropertyChanged("passportDateOfBirth");
					this.OnpassportDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportPlaceOfBirth", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string passportPlaceOfBirth
		{
			get
			{
				return this._passportPlaceOfBirth;
			}
			set
			{
				if ((this._passportPlaceOfBirth != value))
				{
					this.OnpassportPlaceOfBirthChanging(value);
					this.SendPropertyChanging();
					this._passportPlaceOfBirth = value;
					this.SendPropertyChanged("passportPlaceOfBirth");
					this.OnpassportPlaceOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportAuthority", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string passportAuthority
		{
			get
			{
				return this._passportAuthority;
			}
			set
			{
				if ((this._passportAuthority != value))
				{
					this.OnpassportAuthorityChanging(value);
					this.SendPropertyChanging();
					this._passportAuthority = value;
					this.SendPropertyChanged("passportAuthority");
					this.OnpassportAuthorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportDateOfIssue", DbType="DateTime NOT NULL")]
		public System.DateTime passportDateOfIssue
		{
			get
			{
				return this._passportDateOfIssue;
			}
			set
			{
				if ((this._passportDateOfIssue != value))
				{
					this.OnpassportDateOfIssueChanging(value);
					this.SendPropertyChanging();
					this._passportDateOfIssue = value;
					this.SendPropertyChanged("passportDateOfIssue");
					this.OnpassportDateOfIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportDateOfExpiry", DbType="DateTime NOT NULL")]
		public System.DateTime passportDateOfExpiry
		{
			get
			{
				return this._passportDateOfExpiry;
			}
			set
			{
				if ((this._passportDateOfExpiry != value))
				{
					this.OnpassportDateOfExpiryChanging(value);
					this.SendPropertyChanging();
					this._passportDateOfExpiry = value;
					this.SendPropertyChanged("passportDateOfExpiry");
					this.OnpassportDateOfExpiryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportFileName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string passportFileName
		{
			get
			{
				return this._passportFileName;
			}
			set
			{
				if ((this._passportFileName != value))
				{
					this.OnpassportFileNameChanging(value);
					this.SendPropertyChanging();
					this._passportFileName = value;
					this.SendPropertyChanged("passportFileName");
					this.OnpassportFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportContentType", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string passportContentType
		{
			get
			{
				return this._passportContentType;
			}
			set
			{
				if ((this._passportContentType != value))
				{
					this.OnpassportContentTypeChanging(value);
					this.SendPropertyChanging();
					this._passportContentType = value;
					this.SendPropertyChanged("passportContentType");
					this.OnpassportContentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportBytes", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary passportBytes
		{
			get
			{
				return this._passportBytes;
			}
			set
			{
				if ((this._passportBytes != value))
				{
					this.OnpassportBytesChanging(value);
					this.SendPropertyChanging();
					this._passportBytes = value;
					this.SendPropertyChanged("passportBytes");
					this.OnpassportBytesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime NOT NULL")]
		public System.DateTime createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passport_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string passport_status
		{
			get
			{
				return this._passport_status;
			}
			set
			{
				if ((this._passport_status != value))
				{
					this.Onpassport_statusChanging(value);
					this.SendPropertyChanging();
					this._passport_status = value;
					this.SendPropertyChanged("passport_status");
					this.Onpassport_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr_uploader_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string hr_uploader_name
		{
			get
			{
				return this._hr_uploader_name;
			}
			set
			{
				if ((this._hr_uploader_name != value))
				{
					this.Onhr_uploader_nameChanging(value);
					this.SendPropertyChanging();
					this._hr_uploader_name = value;
					this.SendPropertyChanged("hr_uploader_name");
					this.Onhr_uploader_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr_uploader_id", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string hr_uploader_id
		{
			get
			{
				return this._hr_uploader_id;
			}
			set
			{
				if ((this._hr_uploader_id != value))
				{
					this.Onhr_uploader_idChanging(value);
					this.SendPropertyChanging();
					this._hr_uploader_id = value;
					this.SendPropertyChanged("hr_uploader_id");
					this.Onhr_uploader_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
